### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by agentfitz** [alextunyk/json-batch-translate#2]
This project looks very interesting, thanks for putting it together  Question for you, assuming I have a Google Translate API key, what else do I need to get your project to run? I'm a little confused, is this a server side utility, or client side, and what exactly are its dependencies? Thanks!

**Comment by alextunyk** [comment]
json-batch-translate is the library you can use on server side. It provides programming interface to your Java-based application for batch translation per a single request.
